### ISSUE TITLE
Implement Schedule API

### ISSUE THREAD

**Issue by Eleven-Lines** [Eleven-Lines/mikan#2]
# Schedule API
- Contains Some WorkPlan, or just Plan

## todo

- [ ] Create model `Plan`, which is a generalized model of `WorkPlan`
  - contains `date`, `completed_by`, `assigned_*`, `members`
- [ ] Create model  `Schefule`
  - contains some Plan

**Comment by Eleven-Lines** [comment]
- [ ] Separate member assignment as model `members.MemberAssignableModel`
- [ ] Subclass `Schedule` and `Workplan`
