### ISSUE TITLE
Sync schedules with Google Calendar

### ISSUE THREAD

**Issue by Eleven-Lines** [Eleven-Lines/mikan#3]
# overview
- Sync model `Schedule` with Google Calendar
- Admin (not sysad) can configure account

# todo
- [ ] Make `Schedule` suitable for Google Calendar
- [ ] Call API during CRUD operation
- [ ] Set some identifiers on Google Calendar
